packages:
  - 'packages/subscriber'
  - 'packages/__tests__/project1'
  - 'apps/reactjs'
  - 'apps/solidjs'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lightningcss: true

nodeLinker: hoisted

minimumReleaseAge: 300

minimumReleaseAgeExclude:
  - '@bemedev/*'
